# Generated by Django 4.2.4 on 2023-08-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
