# Generated by Django 4.2.4 on 2023-08-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_email_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
